### ISSUE TITLE
Training num_va too large

### ISSUE THREAD

**Issue by vin-ni** [ciaua/unagan#15]
Hello,
why is `num_va = 200` in `train.hierarchical.py`?
It threw an error, because my dataset has only 156 samples. So `va_dataset = VocDataset(va_ids, in_dir)` became 0

I set it down to 100 and now training seems to be working.  Still curious if I can just change that number :)
Thank you!

**Comment by ciaua** [comment]
`num_va` is the number of data used for validation during training. The number should be based on the total amount of data you have. I set `num_va` to 200 based on my training data. People usually use 5~20% of the total amount of data for validation.

If you have only 156 samples, I think a reasonable number for it is around 5~20. As 156 samples is already a very small number for this type of models, I would prefer to keep most data for training and to use a smaller number of data for validation, say, `num_va = 6`.

**Comment by vin-ni** [comment]
Thank you very much! I will try that.

**Comment by vin-ni** [comment]
Thank you very much! I will try that.
