### ISSUE TITLE
Speech seems illegible

### ISSUE THREAD

**Issue by swamiviv** [ciaua/unagan#2]
The generated speech samples provided here just seems illegible, LJ speech is an english speaking dataset, correct?

**Comment by ciaua** [comment]
Indeed they are illegible, which is expected in this work as the samples are generated without conditions

**Comment by swamiviv** [comment]
EDIT: I think I get your point. Do you imply that to generate long range speech, there should be some text based conditioning?

Can you please elaborate? For instance, in the wavegan work, which is unconditional as well, they can generate reasonable spoken words: https://chrisdonahue.com/wavegan_examples/, both with waveGAN as well as specGAN, which predicts the spectrogram and performs an inversion.

**Comment by ciaua** [comment]
In the link you provided, there are two sections that are related to speech, Speech Commands Zero through Nine (SC09) and Large vocabulary speech (TIMIT).

To me, it seems that those in Large vocabulary speech (TIMIT) are illegible.
The spoken numbers in Speech Commands Zero through Nine (SC09) are better recognizable. My conjecture is that maybe it is easier to learn the common patterns in a small dataset with a ten word vocabulary like SC09. As I never run experiments on this dataset, I can't not say for sure though.
