### ISSUE TITLE
How to try my own model?

### ISSUE THREAD

**Issue by etimsijs** [ciaua/unagan#3]
Hello. I tried to make my own dataset from .wav files according to your guide. Everything was ok , but when I tried to start training I got an errors , because the code you provided "hierarchical_with_cycle.py" has this lines:
```class VocDataset(Dataset):
    def __init__(self, ids, path):
        self.metadata = ids
        self.path = path

    def __getitem__(self, index):
        id = self.metadata[index]
        voc_fp = os.path.join(self.path, id, 'vocals.npy')

        voc = np.load(voc_fp)

        return voc
```
It tried to find 101_1/vocals.npy  , but previous steps did files like 101_1.npy,101_2.npy , not a directories like 101_1 with file the vocals.npy into them. 
This was causing errors , but I fixed it by  making directories , with the file vocals.npy in them . Training started successfully . After training I got folder "checkpoints" with the following files and folders:
-model
where are such files
```params.BEGANRecorder.best_Convergence.torch
params.BEGANRecorder.latest.torch
params.Discriminator.best_Convergence.torch
params.Discriminator.latest.torch
params.Encoder.best_Convergence.torch
params.Encoder.latest.torch
params.Generator.best_Convergence.torch
params.Generator.latest.torch
epoch.best_Convergence.txt
```
-record
where are such files
```
record.@1.json
record.@2.json
record.latest.json
```
and this files were in "checkpoints" with the model and record folders
```structure_description.BEGANRecorder.csv
structure_description.Discriminator.csv
structure_description.Encoder.csv
tructure_description.Generator.csv
training_script.py
````

So, my question is , how to generate sound from this trained model ? You provided models.zip with pretrained models but it has nothing in common with the files I got after training.

**Comment by ciaua** [comment]
Hello,

Sorry for the confusion. The problem is that I changed the file extension of the saved parameters some time before, so in fact those with extensions `.torch` and `.pt` are both saved parameters.

Therefore, in order to generate audios with your models, you can replace the path in the `param_fp` variable in `generate.py` with either `params.Generator.best_Convergence.torch` or `params.Generator.latest.torch` in your folder.

**Comment by etimsijs** [comment]
Thank for your work. It works.

**Comment by moiseshorta** [comment]
Hi @etimsijs @ciaua ,

I too have run into an error when training on my own data.

I too have fixed it with this line: 

`        voc_fp = os.path.join(self.path, id)
        voc_fp = voc_fp + ".npy"

        voc = np.load(voc_fp)`

It starts training but then there are no saved outputs in `checkpoint` folder even after training.

Any help would be appreciated!

**Comment by HIN0209** [comment]
FROM (incorrect): voc_fp = os.path.join(self.path, id, 'vocals.npy')
TO (correct): voc_fp = os.path.join(self.path, id+'.npy')
worked for me, not going into the vocals.npy issue.
