### ISSUE TITLE
code hang when I try to run extract_mel.py

### ISSUE THREAD

**Issue by rudxokim** [ciaua/unagan#4]
python wait for nothing when I run extract_mel.py script below.

    for i, (id, length) in enumerate(pool.imap_unordered(process_audios, audio_files), 1):
        print(id)
        if length == 0:
            continue
        dataset += [(id, length)]

loop doesn't start at all. 

maybe because of some package dependencies problem?

I've already encountered dependency error with Numba package and Librosa package.

Would you please share some pip package version and python version?

Much appreciated

**Comment by rudxokim** [comment]
maybe because of the multiprocessing pool..

I'll share my keyboard interrupt log below.

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/unagan37/lib/python3.7/multiprocessing/pool.py", line 733, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "extract_mel.py", line 138, in <module>
    for i, (id, length) in enumerate(pool.imap_unordered(process_audios, audio_files), 1):
  File "/home/ubuntu/anaconda3/envs/unagan37/lib/python3.7/multiprocessing/pool.py", line 737, in next
    self._cond.wait(timeout)
  File "/home/ubuntu/anaconda3/envs/unagan37/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

**Comment by ciaua** [comment]
I just tested the script with a freshly created conda environment with python=3.8.
```
conda create -n newenv python=3.8
conda activate newenv
pip install -r requirements.txt
```

Under this setting, I didn't encounter issues executing `extract_mel.py`
Could you try this setting and see if the issue is resolved?  

Sometimes it is more difficult to debug with multiprocessing. You can also try to run the loop without multiprocessing. For example:
```
for audio_file in audio_files:
    process_audios(audio_file)
```

**Comment by rudxokim** [comment]
Thanks for your prompt response

I've tried 

for audio_file in audio_files:
    process_audios(audio_file)

right away however split error occurs when to perform 

def process_audios(path):
    id = path.split('/')[-1][:-4]

**Comment by ciaua** [comment]
Can you check if the `path` is a string of a valid path?

**Comment by rudxokim** [comment]
I've changed the code in a way that doesn't use multiprocessing. I'm about to inference some audios with my own data. thanks.

I also found out that your code need specific version of 

librosa == 0.6.1
numba == 0.48
