### ISSUE TITLE
Inference with custom trained model

### ISSUE THREAD

**Issue by rudxokim** [ciaua/unagan#5]
Greetings.

I've successfully trained a model with my own data.

however I couldn't understand how I'm gonna use my trained torch params files (records) for generate.py.

![스크린샷 2021-06-08 오후 6 28 20](https://user-images.githubusercontent.com/29219491/121160755-5361f180-c887-11eb-8fe2-beac9b4355c9.png)

It seems like I need pt file to inference 

Thanks.

**Comment by wonyoungseo** [comment]
Hello,

I'm facing exact same issue when trying to generate sample based on custom trained model
Would it be possible to suggest walkthrough in this situation? @ciaua 

Thank you and regards,

**Comment by ciaua** [comment]
Hi, 

Those .torch files are the model parameters

See https://github.com/ciaua/unagan/issues/3#issuecomment-774820967 for more details

**Comment by rudxokim** [comment]
Thanks for your info!..

**Comment by rudxokim** [comment]
Thanks for your info!
