### ISSUE TITLE
Not an issue - question on actually conditioning generated audio

### ISSUE THREAD

**Issue by johndpope** [ciaua/unagan#7]
are there any efforts to actually force the audio to fit a midi sequence that you are aware?

**Comment by ciaua** [comment]
I think the task you described is closer to singing voice synthesis where the score (midi in your case) is given. 
One possible way to achieve what you described is to extract the pitches from the singing voices with tools like Crepe, and then feed the extracted pitches to the model as conditions

**Comment by johndpope** [comment]
Nice idea. I’ll check out crepe - thanks
